# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-18 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20171118_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=['%Y-%m-%d']),
            preserve_default=False,
        ),
    ]
