# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-18 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20171118_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
