# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20171118_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(verbose_name=['%Y-%m-%d']),
        ),
    ]
